### PR TITLE
Fix Issue 14

### PR DESCRIPTION
**Pull request by WtfJoke**
https://github.com/WtfJoke/rtc2git/issues/14
The script was throwing errors like "No repositories found based on path. Specify repository URI." and "Problem running 'discard': Unable to find workspace. Specify workspace."

### CODE REVIEW

**Comment by WtfJoke** [comment]
@ljhaywar I was so rude to create a pull request with your changes on my own. Hope you dont mind :)

**Comment by ljhaywar** [comment]
Not at all.  I'm new to Git and am still figuring out the terminology, so let me know if you need me to do anything.

**Comment by WtfJoke** [comment]
No worries, Im still a git amateur as well :stuck_out_tongue:

**Comment by WtfJoke** [comment]
@ljhaywar Could you please test if your use case still works with my current development-branch?

**Pull request merged**
